[tasks.dev]
script = [
    "cargo install cargo-tarpaulin",
    "cargo install cargo-release",
    "cargo build",
]

[tasks.fmt]
script = "cargo fmt"

[tasks.fmt-commit]
script = [
    "cargo fmt",
    "git add .",
    'git commit -m "style: reformat code with cargo fmt"',
    "git push"
]

[tasks.lint]
script = "cargo clippy --all-targets --all-features --release"

[tasks.full-test]
script = [
    "cargo test",
    "cargo clippy --all-targets --all-features --release",
    "cargo fmt --check"
]

[tasks.deploy-patch]
script = "cargo release patch --execute --no-confirm --no-verify"

[tasks.deploy-patch-dryrun]
script = "cargo release patch --no-confirm --no-verify"

[tasks.changelog]
script = [
    "git add .",
    'git commit -m "chore: update changelog"',
    "git push"
]
