# cargo
[tasks.install-cargo-tarpaulin]
command = "cargo"
args = ["install", "cargo-tarpaulin"]

[tasks.install-cargo-release]
command = "cargo"
args = ["install", "cargo-release"]

[tasks.fmt]
command = "cargo"
args = ["fmt"]



# git
[tasks.git-add-all]
command = "git"
args = ["add", "."]

[tasks.git-commit-env]
command = "git"
args = ["commit", "-m", "${DEFAULT_GIT_COMMIT_MSG}"]

[tasks.git-push]
command = "git"
args = ["push"]

[tasks.dev]
dependencies = [
    "install-cargo-tarpaulin",
    "install-cargo-release",
    "build"
]

[tasks.fmt-commit]
env = { DEFAULT_GIT_COMMIT_MSG = "style: reformat code with cargo fmt" }
dependencies = [
    "fmt",
    "git-add-all",
    "git-commit-env",
    "git-push"
]

[tasks.lint]
script = "cargo clippy --all-targets --all-features --release"

[tasks.full-test]
script = [
    "cargo test",
    "cargo clippy --all-targets --all-features --release",
    "cargo fmt --check"
]

[tasks.deploy-patch]
script = "cargo release patch --execute --no-confirm --no-verify"

[tasks.deploy-patch-dryrun]
script = "cargo release patch --no-confirm --no-verify"

[tasks.changelog]
script = [
    "git add .",
    'git commit -m "chore: update changelog"',
    "git push"
]
